//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSoruCevap.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHAREKET
    {
        public int ID { get; set; }
        public Nullable<int> SORU { get; set; }
        public Nullable<int> HASTA { get; set; }
        public Nullable<int> DOKTOR { get; set; }
        public Nullable<System.DateTime> CEVAPLAMATARIHI { get; set; }
        public Nullable<System.DateTime> GUNCELLEMETARIHI { get; set; }
    
        public virtual TBLUYEHASTA TBLUYEHASTA { get; set; }
    }
}
